In [1]:
# After finding one or two algorithm doing well, improve the performance of the models by tuning the parameters
# to the given dataset.

# 1. Tune the parameters of an Algorithm using grid search that you specify
# 2. Tune the algoritm of an Algo using a random search


In [2]:
# Using grid search to tune parameters on Pima Indians onset of diabetes dataset

In [3]:
# Grid Search for Algorithm Tuning
from pandas import read_csv
import numpy
from sklearn.linear_model import Ridge
from sklearn.model_selection import GridSearchCV


In [4]:
url = "https://goo.gl/bDdBiA"
names = ['preg', 'plas', 'pres', 'skin', 'test', 'mass', 'pedi', 'age', 'class']
dataframe = read_csv(url, names=names)
array = dataframe.values


In [5]:
X = array[:,0:8]
Y = array[:,8]


In [6]:
alphas = numpy.array([1,0.1,0.01,0.001,0.0001,0])
param_grid = dict(alpha=alphas)
model = Ridge()


In [7]:
grid = GridSearchCV(estimator=model, param_grid=param_grid)
grid.fit(X, Y)


GridSearchCV(cv=None, error_score='raise',
       estimator=Ridge(alpha=1.0, copy_X=True, fit_intercept=True, max_iter=None,
   normalize=False, random_state=None, solver='auto', tol=0.001),
       fit_params=None, iid=True, n_jobs=1,
       param_grid={'alpha': array([1.e+00, 1.e-01, 1.e-02, 1.e-03, 1.e-04, 0.e+00])},
       pre_dispatch='2*n_jobs', refit=True, return_train_score='warn',
       scoring=None, verbose=0)

In [8]:
print(grid.best_score_)
print(grid.best_estimator_.alpha)


0.27961755931297233
1.0


In [9]:
from sklearn.model_selection import train_test_split

In [22]:
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.33, random_state=42)

In [62]:
ridge = Ridge(alpha = 1, normalize = False)

In [63]:
ridge.fit(X_train, y_train)

Ridge(alpha=1, copy_X=True, fit_intercept=True, max_iter=None,
   normalize=False, random_state=None, solver='auto', tol=0.001)

In [64]:
predict = ridge.predict(X_test)

In [65]:
predict

array([ 0.33218935,  0.24800074,  0.16804986,  0.21462024,  0.50380282,
        0.46592021, -0.19444381,  0.55118294,  0.54218666,  0.72593522,
        0.30938832,  0.87371701,  0.43302308,  0.33196181,  0.06160683,
        0.39024164,  0.17280163,  0.06855925,  0.79307086,  0.54191049,
        0.2908241 ,  0.08689456,  0.48089888,  0.12077457,  0.52609854,
        0.83572262,  0.16109458, -0.05100682,  0.32286942,  0.15978134,
        0.85117876,  0.81976788,  0.73651039,  0.72769644,  0.56755087,
        0.61537971,  1.01594432,  0.28977064,  0.50244353,  0.63073348,
        0.05680184,  0.55784478,  0.53137569,  0.36211576, -0.0668838 ,
        0.51396988,  0.55470198,  0.26366896,  0.39021712,  1.01588096,
        0.00105442,  0.61265284,  0.75690289,  0.31684661,  0.16841416,
       -0.03523053,  0.72811786, -0.36822841,  0.41002809,  0.705001  ,
        0.65921161,  0.38294652,  0.32870824,  0.2721425 ,  0.09478673,
        0.56389279, -0.00279404,  0.68541811, -0.02910944,  0.70

In [66]:
import numpy as np

In [67]:
predict1 = np.abs(np.round(predict))
predict1

array([0., 0., 0., 0., 1., 0., 0., 1., 1., 1., 0., 1., 0., 0., 0., 0., 0.,
       0., 1., 1., 0., 0., 0., 0., 1., 1., 0., 0., 0., 0., 1., 1., 1., 1.,
       1., 1., 1., 0., 1., 1., 0., 1., 1., 0., 0., 1., 1., 0., 0., 1., 0.,
       1., 1., 0., 0., 0., 1., 0., 0., 1., 1., 0., 0., 0., 0., 1., 0., 1.,
       0., 1., 1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 0.,
       1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 1., 0., 1., 0.,
       1., 1., 1., 0., 0., 1., 0., 0., 0., 0., 0., 1., 0., 0., 1., 0., 0.,
       1., 0., 0., 0., 0., 0., 0., 0., 1., 1., 1., 1., 1., 0., 0., 1., 0.,
       0., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.,
       0., 0., 0., 0., 1., 1., 0., 0., 1., 0., 0., 0., 1., 0., 0., 1., 1.,
       1., 0., 0., 1., 1., 0., 0., 0., 0., 0., 1., 1., 0., 1., 1., 0., 0.,
       0., 1., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.,
       1., 0., 0., 0., 1., 1., 0., 0., 0., 0., 1., 0., 1., 0., 0., 1., 1.,
       0., 0., 0., 0., 1.

In [68]:
from sklearn.metrics import confusion_matrix, classification_report

In [69]:
print (confusion_matrix(y_test, predict1))

[[135  33]
 [ 35  51]]


In [70]:
print (classification_report(y_test, predict1))

             precision    recall  f1-score   support

        0.0       0.79      0.80      0.80       168
        1.0       0.61      0.59      0.60        86

avg / total       0.73      0.73      0.73       254



In [ ]:
# Summary: With grid search we arrived at aplha = 1 for Ridge Algorithm providing good model preformance. So we
# achieved goof parameters tuning. 