In [48]:
# ref: https://elitedatascience.com/python-machine-learning-tutorial-scikit-learn
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn import preprocessing
from sklearn.pipeline import make_pipeline
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.externals import joblib 
import numpy as np

In [5]:
dataset_url = 'http://mlr.cs.umass.edu/ml/machine-learning-databases/wine-quality/winequality-red.csv'
data = pd.read_csv(dataset_url, sep=';')
 
print (data.head())

   fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0            7.4              0.70         0.00             1.9      0.076   
1            7.8              0.88         0.00             2.6      0.098   
2            7.8              0.76         0.04             2.3      0.092   
3           11.2              0.28         0.56             1.9      0.075   
4            7.4              0.70         0.00             1.9      0.076   

   free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                 11.0                  34.0   0.9978  3.51       0.56   
1                 25.0                  67.0   0.9968  3.20       0.68   
2                 15.0                  54.0   0.9970  3.26       0.65   
3                 17.0                  60.0   0.9980  3.16       0.58   
4                 11.0                  34.0   0.9978  3.51       0.56   

   alcohol  quality  
0      9.4        5  
1      9.8        5  
2      9.8        5 

In [6]:
data.shape

(1599, 12)

In [7]:
data.describe()

fixed acidity  volatile acidity  citric acid  residual sugar  \
count    1599.000000       1599.000000  1599.000000     1599.000000   
mean        8.319637          0.527821     0.270976        2.538806   
std         1.741096          0.179060     0.194801        1.409928   
min         4.600000          0.120000     0.000000        0.900000   
25%         7.100000          0.390000     0.090000        1.900000   
50%         7.900000          0.520000     0.260000        2.200000   
75%         9.200000          0.640000     0.420000        2.600000   
max        15.900000          1.580000     1.000000       15.500000   

         chlorides  free sulfur dioxide  total sulfur dioxide      density  \
count  1599.000000          1599.000000           1599.000000  1599.000000   
mean      0.087467            15.874922             46.467792     0.996747   
std       0.047065            10.460157             32.895324     0.001887   
min       0.012000             1.000000              6.000000     0.990070   
25%       0.070000             7.000000             22.000000     0.995600   
50%       0.079000            14.000000             38.000000     0.996750   
75%       0.090000            21.000000             62.000000     0.997835   
max       0.611000            72.000000            289.000000     1.003690   

                pH    sulphates      alcohol      quality  
count  1599.000000  1599.000000  1599.000000  1599.000000  
mean      3.311113     0.658149    10.422983     5.636023  
std       0.154386     0.169507     1.065668     0.807569  
min       2.740000     0.330000     8.400000     3.000000  
25%       3.210000     0.550000     9.500000     5.000000  
50%       3.310000     0.620000    10.200000     6.000000  
75%       3.400000     0.730000    11.100000     6.000000  
max       4.010000     2.000000    14.900000     8.000000

In [8]:
y = data.quality
X = data.drop('quality', axis=1)

In [11]:
X_train, X_test, y_train, y_test = train_test_split(X, y, 
                                                    test_size=0.2, 
                                                    random_state=123, 
                                                    stratify=y)

In [16]:
# Standardization is the process of subtracting the means from each feature and then dividing 
# by the feature standard deviations.
# algorithms assume that all features are centered around zero and have approximately the same variance.
X_train_scaled = preprocessing.scale(X_train)
print (X_train_scaled)

[[ 0.51358886  2.19680282 -0.164433   ...  1.08415147 -0.69866131
  -0.58608178]
 [-1.73698885 -0.31792985 -0.82867679 ...  1.46964764  1.2491516
   2.97009781]
 [-0.35201795  0.46443143 -0.47100705 ... -0.13658641 -0.35492962
  -0.20843439]
 ...
 [-0.98679628  1.10708533 -0.93086814 ...  0.24890976 -0.98510439
   0.35803669]
 [-0.69826067  0.46443143 -1.28853787 ...  1.08415147 -0.35492962
  -0.68049363]
 [ 3.1104093  -0.62528606  2.08377675 ... -1.61432173  0.79084268
  -0.39725809]]


In [18]:
# scaled dataset is indeed centered at zero, with unit variance:
print (X_train_scaled.mean(axis=0))


[ 1.16664562e-16 -3.05550043e-17 -8.47206937e-17 -2.22218213e-17
  2.22218213e-17 -6.38877362e-17 -4.16659149e-18 -2.54439854e-15
 -8.70817622e-16 -4.08325966e-16 -1.17220107e-15]


In [20]:
print (X_train_scaled.std(axis=0))

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [21]:
# as similar transformation cannot be applied on the test data due to diff of mean and STD dev.
# so need to use transformer API

In [22]:
# fit the transformer on training set
# apply the transformation on training set
# apply the transformation on test set

In [23]:
scaler = preprocessing.StandardScaler().fit(X_train)


In [24]:
# scaler has been trained on mean/STD of test set

In [26]:
# confirm the sacled data
X_train_scaled = scaler.transform(X_train)
 
print (X_train_scaled.mean(axis=0))

print (X_train_scaled.std(axis=0))

[ 1.16664562e-16 -3.05550043e-17 -8.47206937e-17 -2.22218213e-17
  2.22218213e-17 -6.38877362e-17 -4.16659149e-18 -2.54439854e-15
 -8.70817622e-16 -4.08325966e-16 -1.17220107e-15]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [27]:
# applying model to test data

In [28]:
X_test_scaled = scaler.transform(X_test)
 
print (X_test_scaled.mean(axis=0))

print (X_test_scaled.std(axis=0))

[ 0.02776704  0.02592492 -0.03078587 -0.03137977 -0.00471876 -0.04413827
 -0.02414174 -0.00293273 -0.00467444 -0.10894663  0.01043391]
[1.02160495 1.00135689 0.97456598 0.91099054 0.86716698 0.94193125
 1.03673213 1.03145119 0.95734849 0.83829505 1.0286218 ]


In [29]:
# even here too the mean is not centered around zero but has unit std deviation

In [38]:
# buid modeling pipeline having standarization for transformation and model to fit
# Declare data preprocessing steps
pipeline = make_pipeline(preprocessing.StandardScaler(), 
                             RandomForestRegressor(n_estimators=100))

In [39]:
# Hyperparameters express "higher-level" structural information about the model, and they are typically set before 
# training the model.
# So tuning is required for better performance

In [41]:
print (pipeline.get_params())

{'memory': None, 'steps': [('standardscaler', StandardScaler(copy=True, with_mean=True, with_std=True)), ('randomforestregressor', RandomForestRegressor(bootstrap=True, criterion='mse', max_depth=None,
           max_features='auto', max_leaf_nodes=None,
           min_impurity_decrease=0.0, min_impurity_split=None,
           min_samples_leaf=1, min_samples_split=2,
           min_weight_fraction_leaf=0.0, n_estimators=100, n_jobs=1,
           oob_score=False, random_state=None, verbose=0, warm_start=False))], 'standardscaler': StandardScaler(copy=True, with_mean=True, with_std=True), 'randomforestregressor': RandomForestRegressor(bootstrap=True, criterion='mse', max_depth=None,
           max_features='auto', max_leaf_nodes=None,
           min_impurity_decrease=0.0, min_impurity_split=None,
           min_samples_leaf=1, min_samples_split=2,
           min_weight_fraction_leaf=0.0, n_estimators=100, n_jobs=1,
           oob_score=False, random_state=None, verbose=0, warm_start=Fals

In [42]:
# Declare hyperparameters to tune
hyperparameters = { 'randomforestregressor__max_features' : ['auto', 'sqrt', 'log2'],
                  'randomforestregressor__max_depth': [None, 5, 3, 1]}

Cross-validation is a process for reliably estimating the performance of a method for building a model by training and evaluating your model multiple times using the same method.

Practically, that "method" is simply a set of hyperparameters in this context.

These are the steps for CV:

Split your data into k equal parts, or "folds" (typically k=10).
Train your model on k-1 folds (e.g. the first 9 folds).
Evaluate it on the remaining "hold-out" fold (e.g. the 10th fold).
Perform steps (2) and (3) k times, each time holding out a different fold.
Aggregate the performance across all k folds. This is your performance metric.
The best practice when performing CV is to include your data preprocessing steps inside the cross-validation loop. This prevents accidentally tainting your training folds with influential data from your test fold.

Here's how the CV pipeline looks after including preprocessing steps:

Split your data into k equal parts, or "folds" (typically k=10).
Preprocess k-1 training folds.
Train your model on the same k-1 folds.
Preprocess the hold-out fold using the same transformations from step (2).
Evaluate your model on the same hold-out fold.
Perform steps (2) - (5) k times, each time holding out a different fold.
Aggregate the performance across all k folds. This is your performance metric.


In [43]:
# Tune model using cross-validation pipeline
# CV is needed to tune hyperparameters like maximum depth

clf = GridSearchCV(pipeline, hyperparameters, cv=10)
 
clf.fit(X_train, y_train)

GridSearchCV(cv=10, error_score='raise',
       estimator=Pipeline(memory=None,
     steps=[('standardscaler', StandardScaler(copy=True, with_mean=True, with_std=True)), ('randomforestregressor', RandomForestRegressor(bootstrap=True, criterion='mse', max_depth=None,
           max_features='auto', max_leaf_nodes=None,
           min_impurity_decr...mators=100, n_jobs=1,
           oob_score=False, random_state=None, verbose=0, warm_start=False))]),
       fit_params=None, iid=True, n_jobs=1,
       param_grid={'randomforestregressor__max_features': ['auto', 'sqrt', 'log2'], 'randomforestregressor__max_depth': [None, 5, 3, 1]},
       pre_dispatch='2*n_jobs', refit=True, return_train_score='warn',
       scoring=None, verbose=0)

In [53]:
# see the best set of parameters
clf.best_params_

{'randomforestregressor__max_depth': None,
 'randomforestregressor__max_features': 'sqrt'}

tuned your hyperparameters appropriately using cross-validation, you can generally get a small performance improvement by refitting the model on the entire training set.

Conveniently, GridSearchCV from sklearn will automatically refit the model with the best set of hyperparameters using the entire training set.

In [55]:
print (clf.refit)
# so no refttting is needed

True


In [54]:
# Evaluate model pipeline on test data
pred = clf.predict(X_test)
print ("R2 score: ", r2_score(y_test, pred))
print ("MSE: ",mean_squared_error(y_test, pred))
 
print ("RMSE: ", np.sqrt( mean_squared_error(y_test, pred)*100))


R2 score:  0.47022119983049837
MSE:  0.34185218749999996
RMSE:  5.8468127000956684


In [ ]:
# as erros are low so model performed well.

In [51]:
# Save model for future use. joblob is more efficient as compared to pickle as it can store large numpy arrays
joblib.dump(clf, 'rf_regressor.pkl')


['rf_regressor.pkl']

In [56]:
# To load sometime later
clf2 = joblib.load('rf_regressor.pkl')

# Predict data set using loaded model
clf2.predict(X_test)


array([6.53, 5.74, 4.98, 5.6 , 6.31, 5.67, 4.95, 4.86, 5.02, 6.06, 5.22,
       5.68, 5.81, 5.14, 5.82, 5.63, 6.71, 5.65, 5.74, 6.97, 5.46, 5.76,
       5.04, 5.97, 5.94, 5.04, 5.47, 5.19, 5.9 , 5.9 , 5.91, 6.56, 6.  ,
       4.99, 5.01, 5.89, 5.05, 6.1 , 4.97, 6.06, 4.92, 5.99, 6.66, 5.14,
       6.21, 5.3 , 5.59, 5.61, 5.15, 6.42, 5.97, 5.23, 5.84, 5.1 , 5.61,
       5.62, 5.37, 5.34, 4.99, 5.18, 5.28, 5.15, 5.1 , 5.85, 5.99, 5.25,
       6.38, 5.08, 5.19, 6.56, 5.72, 5.76, 5.11, 5.04, 5.29, 5.95, 5.29,
       5.14, 5.38, 5.3 , 6.37, 5.73, 6.12, 6.41, 5.11, 6.03, 6.45, 6.1 ,
       5.86, 5.92, 6.01, 5.4 , 6.52, 5.61, 5.73, 5.71, 6.81, 6.72, 5.61,
       6.75, 5.12, 5.44, 5.1 , 6.38, 5.04, 4.83, 5.63, 5.03, 5.79, 5.96,
       5.87, 5.49, 6.07, 5.41, 5.21, 5.19, 5.94, 5.06, 4.93, 5.93, 5.94,
       5.03, 5.73, 6.15, 5.3 , 5.33, 5.32, 6.09, 5.45, 5.46, 5.92, 6.17,
       5.18, 5.39, 5.14, 6.46, 5.02, 5.18, 6.78, 5.5 , 5.25, 5.05, 5.78,
       6.06, 5.28, 5.38, 5.08, 6.56, 5.88, 5.07, 5.