In [1]:
import numpy 

In [16]:
num = numpy.arange(27)
num

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

In [17]:
num.reshape(3,3,3)

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [18]:
# comerting list to numpy array

In [19]:
lst = [[12,45,54,2], [3,90,82], []]
lst


[[12, 45, 54, 2], [3, 90, 82], []]

In [20]:
type(lst)

list

In [21]:
lst1 = numpy.asarray(lst)
lst1


array([list([12, 45, 54, 2]), list([3, 90, 82]), list([])], dtype=object)

In [22]:
type(lst1)

numpy.ndarray

In [26]:
num.shape

(27,)

In [27]:
num = num.reshape(3,3,3)
num

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [28]:
num.shape

(3, 3, 3)

In [30]:
#slicing, indexing
num[0:2,:,:]

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]]])

In [31]:
num[:,1,1]

array([ 4, 13, 22])

In [32]:
num[:]

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [33]:
# iterate thru
for  i in num:
    print (i)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]


In [34]:
# list individual items
for  i in num.flat:
    print (i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


In [37]:
# stacking, concatenating with same dimension
ims = numpy.hstack((num, num))
ims

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17],
        [ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26],
        [18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [50]:
# splitting 
v_split = numpy.vsplit(ims[0],2)
v_split

[array([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]]), array([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])]

In [51]:
v_split[0]

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [52]:
h_split = numpy.hsplit(ims,2)
h_split

[array([[[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8]],
 
        [[ 9, 10, 11],
         [12, 13, 14],
         [15, 16, 17]],
 
        [[18, 19, 20],
         [21, 22, 23],
         [24, 25, 26]]]), array([[[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8]],
 
        [[ 9, 10, 11],
         [12, 13, 14],
         [15, 16, 17]],
 
        [[18, 19, 20],
         [21, 22, 23],
         [24, 25, 26]]])]

In [48]:
h_split[0]

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])