# https://machinelearningmastery.com/time-series-forecasting-methods-in-python-cheat-sheet/

## AR Model
### The method is suitable for univariate time series without trend and seasonal compononents
### The autoregression (AR) method models the next step in the sequence as a linear function of the observations at prior time steps.

### The notation for the model involves specifying the order of the model p as a parameter to the AR function, e.g. AR(p). For example, AR(1) is a first-order autoregression model.

In [2]:
from statsmodels.tsa.ar_model import AR
from random import random

In [4]:
data = [x + random() for x in range(0,100)]
model = AR(data)
model_fit = model.fit()

y_hat = model_fit.predict(len(data), len(data))
print (y_hat)

[ 100.42328047]


## Moving Average (MA)
### The moving average (MA) method models the next step in the sequence as a linear function of the residual errors from a mean process at prior time steps.

### A moving average model is different from calculating the moving average of the time series.

### The notation for the model involves specifying the order of the model q as a parameter to the MA function, e.g. MA(q). For example, MA(1) is a first-order moving average model.

### The method is suitable for univariate time series without trend and seasonal components.



In [11]:
# can be constructed from ARMA model by setting 0th order or AR and 1st order MA
from statsmodels.tsa.arima_model import ARMA
model = ARMA(data, order=(0,1))

model_fit = model.fit()
y_hat = model_fit.predict(len(data), len(data))
print (y_hat)

[ 75.15063517]


### Autoregressive Moving Average (ARMA)
## The Autoregressive Moving Average (ARMA) method models the next step in the sequence as a linear function of the observations and resiudal errors at prior time steps.

## It combines both Autoregression (AR) and Moving Average (MA) models.

## The notation for the model involves specifying the order for the AR(p) and MA(q) models as parameters to an ARMA function, e.g. ARMA(p, q). An ARIMA model can be used to develop AR or MA models.

## The method is suitable for univariate time series without trend and seasonal components.

In [16]:
from statsmodels.tsa.arima_model import ARMA
from random import random

data = [random() for x in range(1,100)]

model = ARMA(data, order=(2,1))
model_fit = model.fit(disp=False)

y_hat = model_fit.predict(len(data), len(data))
print (y_hat)

[ 0.51488352]


### Autoregressive Integrated Moving Average (ARIMA)
## The Autoregressive Integrated Moving Average (ARIMA) method models the next step in the sequence as a linear function of the differenced observations and residual errors at prior time steps.

## It combines both Autoregression (AR) and Moving Average (MA) models as well as a differencing pre-processing step of the sequence to make the sequence stationary, called integration (I).

## The notation for the model involves specifying the order for the AR(p), I(d), and MA(q) models as parameters to an ARIMA function, e.g. ARIMA(p, d, q). An ARIMA model can also be used to develop AR, MA, and ARMA models.

## The method is suitable for univariate time series with trend and without seasonal components.

In [21]:
from statsmodels.tsa.arima_model import ARIMA
from random import random

# contrived dataset
data = [x + random() for x in range(1, 100)]
# fit model
model = ARIMA(data, order=(1, 1, 1))
model_fit = model.fit(disp=False)
y_hat = model_fit.predict(len(data), len(data), typ='levels')

print (y_hat)

[ 100.46140066]


/Users/sulbha/anaconda/lib/python3.6/site-packages/statsmodels/tsa/tsatools.py:650: RuntimeWarning: invalid value encountered in true_divide
  newparams = ((1-np.exp(-params))/(1+np.exp(-params))).copy()
/Users/sulbha/anaconda/lib/python3.6/site-packages/statsmodels/tsa/tsatools.py:651: RuntimeWarning: invalid value encountered in true_divide
  tmp = ((1-np.exp(-params))/(1+np.exp(-params))).copy()


## Seasonal Autoregressive Integrated Moving-Average (SARIMA)
### The Seasonal Autoregressive Integrated Moving Average (SARIMA) method models the next step in the sequence as a linear function of the differenced observations, errors, differenced seasonal observations, and seasonal errors at prior time steps.

### It combines the ARIMA model with the ability to perform the same autoregression, differencing, and moving average modeling at the seasonal level.

### The notation for the model involves specifying the order for the AR(p), I(d), and MA(q) models as parameters to an ARIMA function and AR(P), I(D), MA(Q) and m parameters at the seasonal level, e.g. SARIMA(p, d, q)(P, D, Q)m where “m” is the number of time steps in each season (the seasonal period). A SARIMA model can be used to develop AR, MA, ARMA and ARIMA models.

### The method is suitable for univariate time series with trend and/or seasonal components.

In [29]:
from statsmodels.tsa.statespace.sarimax import SARIMAX

data = [x + random() for x in range(1,100)]

model = SARIMAX(data, order = (1,1,1), seasonal_order=(1,1,1,1))

model_fit = model.fit(disp=False)

y_hat = model_fit.predict(len(data), len(data))
print (y_hat)

[ 100.3896435]


### Seasonal Autoregressive Integrated Moving-Average with Exogenous Regressors (SARIMAX)
The Seasonal Autoregressive Integrated Moving-Average with Exogenous Regressors (SARIMAX) is an extension of the SARIMA model that also includes the modeling of exogenous variables.

Exogenous variables are also called covariates and can be thought of as parallel input sequences that have observations at the same time steps as the original series. The primary series may be referred to as endogenous data to contrast it from the exogenous sequence(s). The observations for exogenous variables are included in the model directly at each time step and are not modeled in the same way as the primary endogenous sequence (e.g. as an AR, MA, etc. process).

The SARIMAX method can also be used to model the subsumed models with exogenous variables, such as ARX, MAX, ARMAX, and ARIMAX.

The method is suitable for univariate time series with trend and/or seasonal components and exogenous variables.

In [30]:
# SARIMAX example
from statsmodels.tsa.statespace.sarimax import SARIMAX
from random import random
# contrived dataset
data1 = [x + random() for x in range(1, 100)]
data2 = [x + random() for x in range(101, 200)]
# fit model
model = SARIMAX(data1, exog=data2, order=(1, 1, 1), seasonal_order=(0, 0, 0, 0))
model_fit = model.fit(disp=False)
# make prediction
exog2 = [200 + random()]
yhat = model_fit.predict(len(data1), len(data1), exog=[exog2])
print(yhat)

[ 100.73202072]


## Vector Autoregression (VAR)
### The Vector Autoregression (VAR) method models the next step in each time series using an AR model. It is the generalization of AR to multiple parallel time series, e.g. multivariate time series.

### The notation for the model involves specifying the order for the AR(p) model as parameters to a VAR function, e.g. VAR(p).

### The method is suitable for multivariate time series without trend and seasonal components.

In [35]:
# VAR example
from statsmodels.tsa.vector_ar.var_model import VAR
from random import random
# contrived dataset with dependency
data = list()
for i in range(100):
    v1 = i + random()
    v2 = v1 + random()
    row = [v1, v2]
    data.append(row)
# fit model
model = VAR(data)
model_fit = model.fit()
# make prediction
yhat = model_fit.forecast(model_fit.y, steps=1)
print(yhat)

[[ 100.44020303  100.99835017]]


## Vector Autoregression Moving-Average (VARMA)
### The Vector Autoregression Moving-Average (VARMA) method models the next step in each time series using an ARMA model. It is the generalization of ARMA to multiple parallel time series, e.g. multivariate time series.

### The notation for the model involves specifying the order for the AR(p) and MA(q) models as parameters to a VARMA function, e.g. VARMA(p, q). A VARMA model can also be used to develop VAR or VMA models.

### The method is suitable for multivariate time series without trend and seasonal components.

In [36]:
# VARMA example
from statsmodels.tsa.statespace.varmax import VARMAX
from random import random
# contrived dataset with dependency
data = list()
for i in range(100):
    v1 = random()
    v2 = v1 + random()
    row = [v1, v2]
    data.append(row)
# fit model
model = VARMAX(data, order=(1, 1))
model_fit = model.fit(disp=False)
# make prediction
yhat = model_fit.forecast()
print(yhat)

/Users/sulbha/anaconda/lib/python3.6/site-packages/statsmodels/tsa/statespace/varmax.py:152: EstimationWarning: Estimation of VARMA(p,q) models is not generically robust, due especially to identification issues.
  EstimationWarning)


[[ 0.42551874  1.05679274]]


/Users/sulbha/anaconda/lib/python3.6/site-packages/statsmodels/base/model.py:508: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  "Check mle_retvals", ConvergenceWarning)


## Vector Autoregression Moving-Average with Exogenous Regressors (VARMAX)
### The Vector Autoregression Moving-Average with Exogenous Regressors (VARMAX) is an extension of the VARMA model that also includes the modeling of exogenous variables. It is a multivariate version of the ARMAX method.

### Exogenous variables are also called covariates and can be thought of as parallel input sequences that have observations at the same time steps as the original series. The primary series(es) are referred to as endogenous data to contrast it from the exogenous sequence(s). The observations for exogenous variables are included in the model directly at each time step and are not modeled in the same way as the primary endogenous sequence (e.g. as an AR, MA, etc. process).

### The VARMAX method can also be used to model the subsumed models with exogenous variables, such as VARX and VMAX.

### The method is suitable for multivariate time series without trend and seasonal components and exogenous variables

In [38]:
from statsmodels.tsa.statespace.varmax import VARMAX
from random import random
# contrived dataset with dependency
data = list()
for i in range(100):
    v1 = random()
    v2 = v1 + random()
    row = [v1, v2]
    data.append(row)
data_exog = [x + random() for x in range(100)]
# fit model
model = VARMAX(data, exog=data_exog, order=(1, 1))
model_fit = model.fit(disp=False)
# make prediction
data_exog2 = [[100]]
yhat = model_fit.forecast(exog=data_exog2)
print(yhat)

[[ 0.51394332  1.07874822]]


## Simple Exponential Smoothing (SES)
### The Simple Exponential Smoothing (SES) method models the next time step as an exponentially weighted linear function of observations at prior time steps.

### The method is suitable for univariate time series without trend and seasonal components.



In [32]:
from statsmodels.tsa.holtwinters import SimpleExpSmoothing

from random import random
# contrived dataset
data = [x + random() for x in range(1, 100)]
# fit model
model = SimpleExpSmoothing(data)
model_fit = model.fit()
# make prediction
yhat = model_fit.predict(len(data), len(data))
print(yhat)

[ 99.10251722]


## Holt Winter’s Exponential Smoothing (HWES)
## The Holt Winter’s Exponential Smoothing (HWES) also called the Triple Exponential Smoothing method models the next time step as an exponentially weighted linear function of observations at prior time steps, taking trends and seasonality into account.

## The method is suitable for univariate time series with trend and/or seasonal components.



In [33]:
# HWES example
from statsmodels.tsa.holtwinters import ExponentialSmoothing
from random import random
# contrived dataset
data = [x + random() for x in range(1, 100)]
# fit model
model = ExponentialSmoothing(data)
model_fit = model.fit()
# make prediction
yhat = model_fit.predict(len(data), len(data))
print(yhat)

[ 99.5671662]


## https://machinelearningmastery.com/taxonomy-of-time-series-forecasting-problems/

## Inputs vs. Outputs
### What are the inputs and outputs for a forecast?
## Endogenous vs. Exogenous
### What are the endogenous and exogenous variables?
## Unstructured vs. Structured
### Are the time series variables unstructured or structured?
## Regression vs. Classification
### Are you working on a regression or classification predictive modeling problem?
## What are some alternate ways to frame your time series forecasting problem?
### Univariate vs. Multivariate
## Are you working on a univariate or multivariate time series problem?
### Single-step vs. Multi-step
## Do you require a single-step or a multi-step forecast?
### Static vs. Dynamic
## Do you require a static or a dynamically updated model?
### Contiguous vs. Discontiguous
## Are your observations contiguous or discontiguous?

## Use below to answer above questions --- 
### Data visualizations (e.g. line plots, etc.).
### Statistical analysis (e.g. ACF/PACF plots, etc.).
### Domain experts.
### Project stakeholders.

## Model Selection
### Baseline.
### Persistence (grid search the lag observation that is persisted)
### Rolling moving average.
…
### Autoregression.
### ARMA for stationary data.
### ARIMA for data with a trend.
### SARIMA for data with seasonality.
…
### Exponential Smoothing.
### Simple Smoothing
### Holt Winters Smoothing

#### This list is based on a univariate time series forecasting problem, but you can adapt it for the specifics of your problem, e.g. use VAR/VARMA/etc. in the case of multivariate time series forecasting. 


Some data preparation schemes to consider include:

Differencing to remove a trend.
Seasonal differencing to remove seasonality.
Standardize to center.
Normalize to rescale.
Power Transform to make normal.
So much searching can be slow.

Some ideas to speed up the evaluation of models include:

Use multiple machines in parallel via cloud hardware (such as Amazon EC2).
Reduce the size of the train or test dataset to make the evaluation process faster.
Use a more coarse grid of hyperparameters and circle back if you have time later.
Perhaps do not refit a model for each step in walk-forward validation.